apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-rolebinding
subjects:
- kind: ServiceAccount
  name: label-sa
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: label-role
  apiGroup: rbac.authorization.k8s.io